name: Deploy Image from Semantic Version

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          build-args: |
            GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            GCLOUD_PROJECT=${{ secrets.GCLOUD_PROJECT }}
            FIREBASE_COLLECTION_IMAGES=${{ secrets.FIREBASE_COLLECTION_IMAGES }}
            NOTION_API_AUTH_TOKEN=${{ secrets.NOTION_API_AUTH_TOKEN }}
            GIT_TAG=${{ env.RELEASE_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}

      - name: Set Context
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set-context cloud_okteto_com --namespace 3trees-seonglae

      - name: Use Context
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: use-context cloud_okteto_com

      - name: Apply Service
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f app/threetrees-svc.yaml

      - name: Apply Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f app/threetrees-deploy.yaml
